/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.notifikazioak.interfazea;

/**
 *
 * @author 1ag3.achralla
 */
public class alertaSortuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form alertaSortuJFrame
     */
    public alertaSortuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tituloajLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        alertarenIzenajTextField1 = new javax.swing.JTextField();
        kokapenaAukeratujLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kokapenakjList1 = new javax.swing.JList<>();
        alertaMotajLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alertaMotakjList2 = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        sortuAlertajButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(9, 0));

        tituloajLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloajLabel1.setForeground(new java.awt.Color(255, 255, 255));
        tituloajLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloajLabel1.setText("SORTU ALERTA BAT");
        jPanel3.add(tituloajLabel1);
        jPanel3.add(jSeparator1);

        alertarenIzenajTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alertarenIzenajTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alertarenIzenajTextField1.setText("IZENDATU ZURE ALERTA");
        jPanel3.add(alertarenIzenajTextField1);

        kokapenaAukeratujLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        kokapenaAukeratujLabel2.setForeground(new java.awt.Color(255, 255, 255));
        kokapenaAukeratujLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kokapenaAukeratujLabel2.setText("KOKAPENA AUKERATU");
        jPanel3.add(kokapenaAukeratujLabel2);

        kokapenakjList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Villabona", "Tolosa", "Donostia", "Gros", "Irun" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(kokapenakjList1);

        jPanel3.add(jScrollPane1);

        alertaMotajLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        alertaMotajLabel3.setForeground(new java.awt.Color(255, 255, 255));
        alertaMotajLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertaMotajLabel3.setText("ALERTA MOTA EZARRI");
        jPanel3.add(alertaMotajLabel3);

        alertaMotakjList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Eguzkitsua", "Euritsua", "Elurra", "Aize fuertea" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(alertaMotakjList2);

        jPanel3.add(jScrollPane2);
        jPanel3.add(jSeparator2);

        sortuAlertajButton1.setText("SORTU");
        jPanel3.add(sortuAlertajButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alertaSortuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alertaSortuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alertaSortuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alertaSortuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alertaSortuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertaMotajLabel3;
    private javax.swing.JList<String> alertaMotakjList2;
    private javax.swing.JTextField alertarenIzenajTextField1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kokapenaAukeratujLabel2;
    private javax.swing.JList<String> kokapenakjList1;
    private javax.swing.JButton sortuAlertajButton1;
    private javax.swing.JLabel tituloajLabel1;
    // End of variables declaration//GEN-END:variables
}
