/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.notifikazioak.interfazea;

/**
 *
 * @author 1ag3.achralla
 */
public class erregistratuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form erregistratuJFrame
     */
    public erregistratuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erregistratujPanel1 = new javax.swing.JPanel();
        erregistratujLabel1 = new javax.swing.JLabel();
        erabiltzaileajLabel1 = new javax.swing.JLabel();
        pasahitzajLabel1 = new javax.swing.JLabel();
        erabiltzaileajTextField1 = new javax.swing.JTextField();
        pasahitzajPasswordField1 = new javax.swing.JPasswordField();
        saioaHasijButton1 = new javax.swing.JButton();
        emailajLabel1 = new javax.swing.JLabel();
        emailajTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        erregistratujPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        erregistratujLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        erregistratujLabel1.setText("ERREGISTRATU");

        erabiltzaileajLabel1.setText("Erabiltzailea");

        pasahitzajLabel1.setText("pasahitza");

        erabiltzaileajTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erabiltzaileajTextField1ActionPerformed(evt);
            }
        });

        saioaHasijButton1.setText("erregistratu");

        emailajLabel1.setText("emaila");

        javax.swing.GroupLayout erregistratujPanel1Layout = new javax.swing.GroupLayout(erregistratujPanel1);
        erregistratujPanel1.setLayout(erregistratujPanel1Layout);
        erregistratujPanel1Layout.setHorizontalGroup(
            erregistratujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erregistratujPanel1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(erregistratujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erregistratujPanel1Layout.createSequentialGroup()
                        .addComponent(erabiltzaileajLabel1)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erregistratujPanel1Layout.createSequentialGroup()
                        .addGroup(erregistratujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(erregistratujLabel1)
                            .addComponent(pasahitzajPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(erabiltzaileajTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(emailajTextField1))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erregistratujPanel1Layout.createSequentialGroup()
                        .addComponent(pasahitzajLabel1)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erregistratujPanel1Layout.createSequentialGroup()
                        .addComponent(saioaHasijButton1)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erregistratujPanel1Layout.createSequentialGroup()
                        .addComponent(emailajLabel1)
                        .addGap(180, 180, 180))))
        );
        erregistratujPanel1Layout.setVerticalGroup(
            erregistratujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erregistratujPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(erregistratujLabel1)
                .addGap(18, 18, 18)
                .addComponent(erabiltzaileajLabel1)
                .addGap(18, 18, 18)
                .addComponent(erabiltzaileajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pasahitzajLabel1)
                .addGap(18, 18, 18)
                .addComponent(pasahitzajPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailajLabel1)
                .addGap(18, 18, 18)
                .addComponent(emailajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(saioaHasijButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(erregistratujPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(erregistratujPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void erabiltzaileajTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erabiltzaileajTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_erabiltzaileajTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(erregistratuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(erregistratuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(erregistratuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(erregistratuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new erregistratuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailajLabel1;
    private javax.swing.JTextField emailajTextField1;
    private javax.swing.JLabel erabiltzaileajLabel1;
    private javax.swing.JTextField erabiltzaileajTextField1;
    private javax.swing.JLabel erregistratujLabel1;
    private javax.swing.JPanel erregistratujPanel1;
    private javax.swing.JLabel pasahitzajLabel1;
    private javax.swing.JPasswordField pasahitzajPasswordField1;
    private javax.swing.JButton saioaHasijButton1;
    // End of variables declaration//GEN-END:variables
}
