/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.notifikazioak.interfazea;

/**
 *
 * @author 1ag3.achralla
 */
public class logeatuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginJFrame
     */
    public logeatuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginjPanel1 = new javax.swing.JPanel();
        logeatujLabel1 = new javax.swing.JLabel();
        erabiltzaileajLabel1 = new javax.swing.JLabel();
        pasahitzajLabel1 = new javax.swing.JLabel();
        erabiltzaileajTextField1 = new javax.swing.JTextField();
        pasahitzajPasswordField1 = new javax.swing.JPasswordField();
        saioaHasijButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginjPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        logeatujLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logeatujLabel1.setText("LOGEATU");

        erabiltzaileajLabel1.setText("Erabiltzailea");

        pasahitzajLabel1.setText("pasahitza");

        erabiltzaileajTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erabiltzaileajTextField1ActionPerformed(evt);
            }
        });

        saioaHasijButton1.setText("saioa hasi");

        javax.swing.GroupLayout loginjPanel1Layout = new javax.swing.GroupLayout(loginjPanel1);
        loginjPanel1.setLayout(loginjPanel1Layout);
        loginjPanel1Layout.setHorizontalGroup(
                loginjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginjPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(logeatujLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginjPanel1Layout.createSequentialGroup()
                                .addContainerGap(121, Short.MAX_VALUE)
                                .addGroup(loginjPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginjPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(loginjPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(loginjPanel1Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(pasahitzajLabel1))
                                                        .addComponent(erabiltzaileajLabel1))
                                                .addGap(167, 167, 167))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginjPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(loginjPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(pasahitzajPasswordField1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(erabiltzaileajTextField1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(116, 116, 116))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                loginjPanel1Layout.createSequentialGroup()
                                                        .addComponent(saioaHasijButton1)
                                                        .addGap(156, 156, 156)))));
        loginjPanel1Layout.setVerticalGroup(
                loginjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginjPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logeatujLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(erabiltzaileajLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(erabiltzaileajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(pasahitzajLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(pasahitzajPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
                                        Short.MAX_VALUE)
                                .addComponent(saioaHasijButton1)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void erabiltzaileajTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_erabiltzaileajTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_erabiltzaileajTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logeatuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logeatuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logeatuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logeatuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logeatuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erabiltzaileajLabel1;
    private javax.swing.JTextField erabiltzaileajTextField1;
    private javax.swing.JLabel logeatujLabel1;
    private javax.swing.JPanel loginjPanel1;
    private javax.swing.JLabel pasahitzajLabel1;
    private javax.swing.JPasswordField pasahitzajPasswordField1;
    private javax.swing.JButton saioaHasijButton1;
    // End of variables declaration//GEN-END:variables
}
